### ISSUE TITLE
Catch exceptions and present them to the user

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/atomkraft#107]
Currently, all exceptions are propagated to the top level and thrown to the user. 

As an example, when following the [Transfer tutorial](https://github.com/informalsystems/atomkraft/blob/31b3e35057e48c524dcd88d156a9dd4cdcf15bb4/examples/cosmos-sdk/transfer/transfer.md), and adding `*` at the line of `Ex` operator in `transfer.tla`, `Modelator` throws a parsing exception that propagates to the user:

```
... stack trace ...
ModelParsingError: Parse error at ./models/transfer.tla:39:
Encountered "====" at line 39, column 1 and token "*" ****
```

We should add a catch-all clause at the top level  of Atomkraft (probably at the CLI), which would catch the exceptions and present them to the user properly.

**Comment by rnbguy** [comment]
@hvanz and I discussed this. We concluded that we need these exception tracebacks for debugging. So I propose an environment variable to make this conditional.

From [StackOverflow](https://stackoverflow.com/a/27674608), 
```
def exception_handler(exception_type, exception, traceback, debug_hook=sys.excepthook):
    if _your_debug_flag_here:
        debug_hook(exception_type, exception, traceback)
    else:
        print "%s: %s" % (exception_type.__name__, exception)

sys.excepthook = exception_handler
```

We can also achieve the same by setting `sys.tracebacklimit=0`.
```
>>> import sys
>>> sys.tracebacklimit=0
>>> int('a')
ValueError: invalid literal for int() with base 10: 'a'
```
