### ISSUE TITLE
CLI param for number of tests to generate from a model and a test scenario

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/atomkraft#130]
Currently, `test model` takes a model and a list of test scenarios to produce one test (from the latest trace) per test scenario.

Atomkraft is supposed to execute on multiple traces - not just the latest trace.

So a `--max-traces` flag should be added to mention the number of traces that Atomkraft will generate and run tests on them.

**Comment by andrey-kuprianov** [comment]
As I've commented in https://github.com/informalsystems/atomkraft/pull/131#issuecomment-1237286462, let's use `--max-trace`, if possible.
