### ISSUE TITLE
Running cosmwasm example

### ISSUE THREAD

**Issue by djordjepesic1991** [informalsystems/atomkraft#133]
Hello,
I have downloaded atomkraft (dev branch). I succeeded to install python3.10 alongside with python3.8 (default version on my ubuntu 20). I compiled project with poetry, following instructions in CONTRIBUTING.md.
I have a problem to run cosmwasm example, which is placed inside the project. I tried first step 
pip install -U atomkraft
but it fails with

Defaulting to user installation because normal site-packages is not writeable
Collecting atomkraft
  Using cached atomkraft-0.0.10-py3-none-any.whl (38 kB)
Collecting case-converter<2.0.0,>=1.1.0
  Using cached case_converter-1.1.0-py3-none-any.whl (14 kB)
Collecting terra-sdk<4.0.0,>=3.0.1
  Using cached terra_sdk-3.0.1-py3-none-any.whl (124 kB)
Collecting terra-proto<3.0.0,>=2.1.0
  Using cached terra_proto-2.1.0-py3-none-any.whl (132 kB)
Collecting tomlkit<0.12.0,>=0.11.1
  Using cached tomlkit-0.11.4-py3-none-any.whl (35 kB)
Collecting modelator<0.7.0,>=0.6.2
  Using cached modelator-0.6.2-py3-none-any.whl (51 kB)
Collecting tabulate<0.9.0,>=0.8.9
  Using cached tabulate-0.8.10-py3-none-any.whl (29 kB)
Collecting websockets<11.0,>=10.3
  Using cached websockets-10.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (111 kB)
Collecting pytest-reportlog<0.2.0,>=0.1.2
  Using cached pytest_reportlog-0.1.2-py3-none-any.whl (5.6 kB)
Collecting hdwallet<3.0.0,>=2.1.1
  Using cached hdwallet-2.1.1-py3-none-any.whl (68 kB)
Collecting copier<7.0.0,>=6.1.0
  Using cached copier-6.1.0-py3-none-any.whl (34 kB)
Collecting GitPython<4.0.0,>=3.1.27
  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting typer[all]<0.7.0,>=0.6.1
  Using cached typer-0.6.1-py3-none-any.whl (38 kB)
Collecting bip-utils<3.0.0,>=2.3.0
  Using cached bip_utils-2.6.1.tar.gz (329 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I don't know how to run an example, using my local compiled version.

**Comment by rnbguy** [comment]
Hey @djordjepesic-ethernal, first of all, thanks for trying it out :+1: Atomkraft's first external issue on the repo :pray: :tada:

Can you provide me the outputs of the following commands,

- `pip -V`
- `python -c "import setuptools; print(setuptools.__version__)"`

**Comment by djordjepesic1991** [comment]
pip -V
Output: pip 22.2.2 from /home/djordjepesic/.local/lib/python3.10/site-packages/pip (python 3.10)

python -c "import setuptools; print(setuptools.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils.core'

**Comment by djordjepesic1991** [comment]
Solution:
pip uninstall setuptools and call apt update && apt upgrade && apt install python-setuptools

Uninstal setuptools version tied to python3.8 (default for ubuntu) and install new setuptools version
