### ISSUE TITLE
No fees by default

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/atomkraft#148]
For our testnets, we should have no fees by default since all our models for now are not modelling fees. (Alternatively, we should model fees in the models).
This is important for PR #147 .

**Comment by ivan-gavran** [comment]
Relevant discussion thus far: in PR #147

**Comment by rnbguy** [comment]
@andrey-kuprianov I need some feedback from you regarding this.

**Comment by ivan-gavran** [comment]
This is taken care of by [this commit](https://github.com/informalsystems/atomkraft/pull/147/commits/6679c806bc116ead6f04a3913be8e5b33dc220f1)
