### ISSUE TITLE
vscode plugins question

### ISSUE THREAD

**Issue by niuzhi** [informalsystems/atomkraft#196]
Hello, may I ask what plugin of vscode is used to replace itf.json into a state diagram in the video, it feels very convenient, please let me know, thank you

https://www.youtube.com/watch?v=EBPypESyzqo

![image](https://user-images.githubusercontent.com/33443724/203746080-fc4e2732-84e7-49db-af66-8b7b2745eff5.png)

**Comment by ivan-gavran** [comment]
Hi @niuzhi ! Here is the plugin from the video: [link](https://marketplace.visualstudio.com/items?itemName=informal.itf-trace-viewer)
