### ISSUE TITLE
Sampling of models fails

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/atomkraft#38]
I have done the following:

1. copy `HelloFull.tla` and `HelloFull.config.toml` from [modelator samples](https://github.com/informalsystems/modelator/tree/dev/modelator/samples) into `tests/models` dir of `atomkraft`.
2. `atomkraft model load tests/models/HelloFull.tla`
3. `atomkraft model sample --config-path tests/models/HelloFull.config.toml`

This fails with `FileNotFoundError: [Errno 2] No such file or directory: '/Users/.../atomkraft/modelator/samples'`

The problem is that the path `modelator/samples` is picked up from the configuration, and overwrites the loaded model.

**Comment by hvanz** [comment]
~~From which branch are you running this?~~
The problem is in the toml file, which has the line:
```
model_path = "modelator/samples/HelloFull.tla"
```
When running the CLI from atomkraft's root directory, the line should be:
```
model_path = "tests/models/HelloFull.tla"
```

**Comment by andrey-kuprianov** [comment]
I see... Ok, let's close this for now. We will return to the issue later: my feeling is that the combination of CLI arguments & config values needs to be optimized to exclude pathological combinations.
