### ISSUE TITLE
Run authz module tests

### ISSUE THREAD

**Issue by tesnimab** [informalsystems/atomkraft#72]
Work has been conducted on the **authz module** using the previous version of Atomkraft.
It could be fine in this repository:
https://github.com/rnbguy/Authz-Audit

In order to validate the prototype, we have to transpose the work in the new version.
It will also allow prioritise the next developments in terms of bug fixing, enhancements and new features.

_First step: Tests execution_
This part is crucial to get users feedback.
- [x] Create new repo
- [x] Configuration to set-up the testnet (that could be used by default as a replacement of the Docker part)
- [x] Write reactors (authz and bank) : We can start by the transactions we need and identify the missing parts, if any, regarding the modules APIs.
- [x] Import the traces and executing them 
- [ ] Result processing

_Second step: Traces generation_
- [ ] Traces generation from existing model
- [x] Optimising model and traces format : The existing model wasn't written originally for end-to-end testing but unit testing. The model could be cleaned up to better understand the logic and generate traces with only the necessary information needed for testing.

**Comment by rnbguy** [comment]
First version of [Mirel's authz reactor](https://github.com/informalsystems/Authz-Audit/blob/main/Authz-Atomkraft/examples/cosmos-sdk/exec-trace.py) port is live [here](https://github.com/informalsystems/atomkraft-cosmos/blob/main/reactors/reactor.py).

**Comment by hvanz** [comment]
Potential new features after discussion between Rano, Tesnim and Hernán:
- Predictable data structure in action steps for easy integration.
- Probably implement Python data classes for direct deserialization.
- Use the same class to implement a method that returns a summary - def summy(self): str.
- Init action step should be processed in atomkraft library to setup the testnet.
- Repeat codes at the beginning and end of each reactor should happen in Atomkraft library, hidden away from the reactor file.
- These codes can include user-defined invariant checks, expected outcome comparisons, etc.
