### ISSUE TITLE
Create an E2E test for Atomkraft

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/atomkraft#76]
We need to add an E2E test in CI, which successfully

- installs Atomkraft
- initializes an Atomkraft project
- generates traces from a model
- creates a reactor
- sets up a chain
- executes a traces on live testnet

**Comment by rnbguy** [comment]
@hvanz does it make sense to use the code snippets from #78 for an E2E test? Maybe using `.mdx`?

**Comment by hvanz** [comment]
Yes, I was thinking that the code in our tutorials should be automatically tested. I think we can run all the steps in the issue description in an `mdx` file, though I haven't tried myself.
