### ISSUE TITLE
Update Transfer tutorial to download Apalache through CLI

### ISSUE THREAD

**Issue by hvanz** [informalsystems/atomkraft#89]
Modelator CLI now has the command `check-apalache-jar` that downloads Apalache jar file if it doesn't exist.

Tutorial file: https://github.com/informalsystems/atomkraft/blob/dev/examples/cosmos-sdk/transfer/transfer.md

**Comment by ivan-gavran** [comment]
This is a part of a bigger issue #92 , closing this one
