### ISSUE TITLE
Improve the transfer tutorial

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/atomkraft#92]
At the moment, the [transfer tutorial](https://github.com/informalsystems/atomkraft/blob/dev/examples/cosmos-sdk/transfer/transfer.md) is the best place for seeing how atomkraft works.

However, it should be updated with respect to recent changes (e.g., not downloading model checkers directly, but through atomkraft etc.).

Overall goal is to have it as a simple tutorial in which everything is done through atomkraft..

**Comment by ivan-gavran** [comment]
Related issues:
 - https://github.com/informalsystems/modelator/issues/241
 - https://github.com/informalsystems/modelator/issues/243
 - https://github.com/informalsystems/atomkraft/issues/88

**Comment by hvanz** [comment]
It's possible to disable the Copy button on GitHub: https://github.com/squidfunk/mkdocs-material/issues/2418

**Comment by ivan-gavran** [comment]
I see the copy button as a feature. Not sure that it makes sense to disable a user-feature for the sake our e2e tests.

Would it make sense to generate a duplicate file? (Then we are certain there will be no divergence.)
